// Template regressions only. Native WKWebView checks remain a separate verification.
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const nodes = new Map();
function node() { return { hidden: false, innerHTML: '', textContent: '', scrollTop: 0, classList: { toggle() {}, add() {}, remove() {} }, style: { setProperty() {} }, setAttribute() {}, addEventListener() {}, focus() {}, querySelector() { return node(); }, querySelectorAll() { return []; } }; }
const context = { window: {innerHeight: 860, addEventListener() {}}, localStorage: {getItem() {return null;}, setItem() {}}, document: {getElementById(id) { if (!nodes.has(id)) nodes.set(id,node()); return nodes.get(id); }, documentElement: node(), querySelector: node, querySelectorAll() {return [];}, addEventListener() {}}, setTimeout() {}, clearTimeout() {}, Intl, Date };
let source = fs.readFileSync(path.join(__dirname, '../Resources/Web/app.js'), 'utf8');
source = source.replace("  post('ready');", `window.test = { load(value) {state=value;}, permissionsPage, preferences, toolBadge, toolDetail, toolLead, toolCard, functionsPage, accessibilityPage, finish, diff, setFilter(value) {preferenceFilter=value;}, setPage(value) {page=value;} };`);
vm.runInNewContext(source, context);
const api = context.window.test;
const base = {busy:false, permissionsCheckedAt:1, permissions:[], settings:[], selected:[], completed:[], preferenceResults:{}, toolResults:{}};
api.load({...base, permissions:[{name:'Full Disk Access',status:'unknown',detail:'Could not confirm',usedBy:'Gestures'}]});
assert.match(api.permissionsPage(), /0 allowed · 0 need attention · 1 unknown/);
assert.doesNotMatch(api.permissionsPage(), /Nothing is blocking a setup step|All listed checks passed|Everything .* allowed/);
const setting = {id:'one',section:'defaults',group:'Finder',description:'Example',domain:'example',key:'key',value:'true'};
api.setPage('defaults');
api.load({...base,settings:[setting], selected:['one'],preferenceResults:{one:{current:'<script>',status:'change',detail:'',checkedAt:1}}});
assert.match(api.preferences(), /Current: <\/span><code class="value was" title="&lt;script&gt;">&lt;script&gt;<\/code>/);
assert.match(api.preferences(), /Proposed: <\/span><code class="value" title="true">true<\/code>/);
assert.match(api.preferences(), /<b>1<\/b> would change · <b>0<\/b> already set/);
assert.match(api.preferences(), /class="primary" data-action="apply"/);
api.setFilter('failed');
assert.match(api.preferences(), /0 shown · 1 selected on this page/);
assert.doesNotMatch(api.preferences(), /data-setting="one"/);
api.setFilter('change');
assert.match(api.preferences(), /data-setting="one"/);
api.load({...base,settings:[setting],selected:['one']});
assert.match(api.preferences(), /class="primary" data-action="check"/);
assert.doesNotMatch(api.preferences(), /Current: /);
api.load({...base,toolResults:{deno:{status:'installed',version:'2.0',path:'/fixture/deno',detail:'',checkedAt:1},bun:{status:'missing',version:'',path:null,detail:'',checkedAt:1}}});
assert.match(api.toolBadge('deno'), /Detected/);
assert.match(api.toolDetail('deno'), /\/fixture\/deno/);
assert.match(api.toolBadge('uv'), /Not checked/);
assert.equal(api.toolDetail('uv'), '');
const tool = id => api.toolCard({id, name:id, command:'echo <install>'}, {lead: api.toolLead(id)});
assert.match(tool('uv'), /class="primary" data-action="toolCheck"/);
assert.match(tool('bun'), /class="primary" data-action="installer"/);
assert.doesNotMatch(tool('deno'), /class="primary"/);
assert.match(tool('uv'), /echo &lt;install&gt;/);
console.log('Web template tests passed: unknown permissions, escaped current values, filters, selection counts, installer states and the leading button.');

// Use the real choice catalog so menu labels and default options stay covered.
const choices = JSON.parse(fs.readFileSync(path.join(__dirname, '../Resources/Config/choices.json'), 'utf8'));
const picks = Object.fromEntries(choices.map(row => [row.id, row.value]));
api.setPage('defaults');
api.setFilter('all');
api.load({...base, settings:choices, choices:picks});
let choiceHTML = api.preferences();
assert.equal((choiceHTML.match(/<option value="dark" selected>/g) || []).length, 2);
assert.match(choiceHTML, /data-choice="appearance" aria-label="Appearance"/);
assert.match(choiceHTML, /data-choice="icon-style" aria-label="Icon &amp; widget style"/);
assert.match(choiceHTML, /<option value="auto" >Auto<\/option>/);
assert.match(choiceHTML, /<option value="tinted-auto" >Tinted \(auto\)<\/option>/);
assert.doesNotMatch(choiceHTML, /data-setting="(?:appearance|icon-style)" checked/);
api.load({...base, settings:choices, choices:{...picks, appearance:'auto'}, preferenceResults:{appearance:{current:'Dark',status:'change',detail:'',checkedAt:1}}});
choiceHTML = api.preferences();
assert.match(choiceHTML, /<option value="auto" selected>Auto<\/option>/);
assert.match(choiceHTML, /class="value was" title="Dark">Dark<\/code>/);
assert.match(choiceHTML, /Would change/);
api.load({...base, busy:true, settings:choices, choices:picks});
choiceHTML = api.preferences();
assert.equal((choiceHTML.match(/<select data-choice="[^"]+"[^>]* disabled>/g) || []).length, 2);
assert.equal((choiceHTML.match(/data-setting="(?:appearance|icon-style)"\s+disabled/g) || []).length, 2);
console.log('Choice templates passed: dark defaults, option labels, independent selection, current values and busy controls.');

api.load({...base,shellPath:'/fixture/.zshrc',functions:[{id:'killport',name:'killport',description:'Stop a port',usage:'killport <port>',code:'killport() { echo "$1"; }',requirements:['~/script.py']}],functionStatuses:[{id:'killport',status:'conflict',detail:'Existing definition',missing:['~/script.py']}]});
assert.match(api.functionsPage(), /killport &lt;port&gt;/);
assert.match(api.functionsPage(), /Missing script/);
assert.match(api.functionsPage(), /<button disabled>Add to \.zshrc<\/button>/);
assert.match(api.functionsPage(), /functionPreview/);
assert.match(api.diff('+a<b\n-c\n@@ x\n d'), /<span class="add">\+a&lt;b<\/span><span class="del">-c<\/span><span class="meta">@@ x<\/span><span class=""> d<\/span>/);
console.log('Shell function templates passed: usage escaping, missing dependencies, conflict state, preview action and diff lines.');

api.load({...base,accessibilityActions:[{id:'speech',name:'Speak selection',description:'Read text',settingsID:'speech',path:'Accessibility > Read & Speak',script:'echo "<safe>"',prompt:'Enable only <this>',help:'https://support.apple.com/guide/mac-help/mh27448/mac'}]});
const accessibility = api.accessibilityPage();
assert.match(accessibility, /Enable with AppleScript/);
assert.match(accessibility, /GPT-6 Luna/);
assert.match(accessibility, /accessibilityRunScript/);
assert.match(accessibility, /accessibilityCodex/);
assert.match(accessibility, /&lt;safe&gt;/);
assert.match(accessibility, /Enable only &lt;this&gt;/);
api.setPage('gestures');
assert.doesNotMatch(api.preferences(), /Open Read &amp; Speak|Enable with AppleScript/);
assert.match(accessibility, /accessibilityRunCLI/);
assert.match(accessibility, /Copy CLI command/);
console.log('Accessibility page: four methods, escaped scripts/prompts and old-page removal passed.');

api.load({...base,completed:['clt']});
assert.match(api.finish('clt'), /checked.*class="primary" data-page="tools">Next: CLI tools/);
assert.match(api.finish('gestures'), /<button\s+data-page="overview">Back to Overview/);
console.log('Finish bar: next step named, and leading once the step is ticked.');
